sources:
  youtube:
    - name: OpenAI
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCXZCJLdBC09xxGZ6gcdrc6A
    - name: Fireship
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA
    - name: Sonny Sangha
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCqeTj_QAnNlmt7FwzNwHZnA
    - name: David Ondrej
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCPGrgwfbkjTIgPoOh2q1BAg
    - name: Two Minute Papers
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg
    - name: ThePrimeagen
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UC8ENHE5xdFSwx71u3fDH5Xw
    - name: Joma Tech
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCV0qA-eDDICsRR9rPcnG7tw
    - name: Marques Brownlee
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCBJycsmduvYEL83R_U4JriQ
    - name: Andrej Karpathy
      rss: https://www.youtube.com/feeds/videos.xml?channel_id=UCgBncpylJ1kiVaPyP-PZauQ
